import 'dart:io';

import 'amiga_model.dart';
import 'config_generator.dart';
import 'host_paths.dart';
import 'file_category.dart';
import 'media_library.dart';
import 'media_root.dart';
import 'emulator_settings.dart';

/// A saved setup on the shelf.
class SavedConfig {
  const SavedConfig({
    required this.name,
    required this.path,
    required this.model,
    required this.summary,
    this.mediaPaths = const <String>[],
  });

  final String name;
  final String path;

  /// Best guess at the machine, read back from the config. Null when the file
  /// predates us or names a machine we do not know.
  final AmigaModel? model;

  /// One line describing what is in the drives, for the shelf card.
  final String summary;

  /// Every file this setup refers to - floppies, hard drives, CD, Kickstart.
  /// The library uses it to tell which games already have a setup, since a
  /// game can only be played through one.
  final List<String> mediaPaths;

  bool uses(String path) => mediaPaths.contains(path);

  /// The WHDLoad archive this setup runs, if it is a WHDLoad setup. The core
  /// needs it as an argument, not just as a config key - see
  /// Emulator.launchConfig.
  String get whdloadArchive {
    for (final String path in mediaPaths) {
      final String lower = path.toLowerCase();
      if (lower.endsWith('.lha') || lower.endsWith('.lzx')) return path;
    }
    return '';
  }
}

/// Where saved setups live, and how they get there.
///
/// Files are plain .uae text in a conf/ directory beside the app's other
/// data, which is also where the core looks when handed --config.
class ConfigStore {
  const ConfigStore._();

  static const String currentSettingsFile = '.current_settings.uae';

  static Future<Directory> configDirectory() async {
    final Directory dir = Directory('${await HostPaths.appSupport()}/conf');
    if (!dir.existsSync()) {
      dir.createSync(recursive: true);
    }
    return dir;
  }

  /// A filename for [name], keeping as much of it as a filesystem allows.
  ///
  /// Brackets are kept: setups are named "Lotus Turbo Challenge (Amiga 500)"
  /// by default, and replacing the parentheses with underscores turned every
  /// name on the shelf into "Lotus Turbo Challenge _Amiga 500_". Only the
  /// characters that actually break a path are replaced.
  static String _sanitise(String name) {
    final String cleaned = name
        .trim()
        .replaceAll(RegExp(r'[/\\:*?"<>|]'), '_')
        .trim();
    return cleaned.isEmpty ? 'Untitled' : cleaned;
  }

  /// Re-points every stored path at this install before the config is
  /// written. See HostPaths.repair: on iOS the app's container UUID changes
  /// with every install, so a setup made yesterday names files by a path that
  /// no longer exists. Doing it here means both new setups and ones already on
  /// the shelf heal the next time they are launched.
  static Future<EmulatorSettings> _repairPaths(EmulatorSettings settings) async {
    final List<String> hardDrives = <String>[
      for (final String drive in settings.hardDrives) await HostPaths.repair(drive),
    ];
    return settings.copyWith(
      romFile: await HostPaths.repair(settings.romFile),
      romExtFile: await HostPaths.repair(settings.romExtFile),
      floppy0: await HostPaths.repair(settings.floppy0),
      floppy1: await HostPaths.repair(settings.floppy1),
      floppy2: await HostPaths.repair(settings.floppy2),
      floppy3: await HostPaths.repair(settings.floppy3),
      cdImage: await HostPaths.repair(settings.cdImage),
      hardDrives: hardDrives,
    );
  }

  /// Writes [settings] as `<name>.uae` and returns the file.
  static Future<File> save(EmulatorSettings settings, String name) async {
    final Directory dir = await configDirectory();
    final File file = File('${dir.path}/${_sanitise(name)}.uae');
    file.writeAsStringSync(ConfigGenerator.generate(await _repairPaths(settings)));
    return file;
  }

  /// Writes the scratch config used for a one-off launch that is not being
  /// added to the shelf. Leading dot keeps it out of the listing.
  static Future<File> saveCurrent(EmulatorSettings settings) async {
    final Directory dir = await configDirectory();
    final File file = File('${dir.path}/$currentSettingsFile');
    file.writeAsStringSync(ConfigGenerator.generate(await _repairPaths(settings)));
    return file;
  }

  /// Re-points the file paths inside an already-written .uae at this install,
  /// rewriting the file if anything moved. Returns the same path either way.
  ///
  /// _repairPaths handles a config as it is generated; this handles one that
  /// was generated by a previous install, which is the case that actually
  /// bites: the shelf launches the saved file directly, so nothing regenerates
  /// it. Working on the text rather than the fields means every path-valued
  /// key is covered - Kickstart, all four floppies, CD, hardfiles - including
  /// ones a future core adds.
  static Future<String> repairConfigFile(String configPath) async {
    final File file = File(configPath);
    if (!file.existsSync()) return configPath;

    String text = file.readAsStringSync();
    final String original = text;

    final String container = File(await HostPaths.documents()).parent.path;
    text = text.replaceAllMapped(
      _containerPrefix,
      (Match m) => '$container/',
    );

    text = await _relocateMissingMedia(text);
    text = await _addMissingRoms(text);

    if (text != original) {
      file.writeAsStringSync(text);
    }
    return configPath;
  }

  /// Fills in ROMs a config was saved without.
  ///
  /// Setups written before the wizard asked CD consoles for their ROMs have
  /// neither a Kickstart nor an extended ROM, and the core does not report
  /// that: it starts, maps no ROM and shows nothing. Rather than make the user
  /// rebuild the setup, the ROMs are chosen the same way the wizard now
  /// chooses them.
  static Future<String> _addMissingRoms(String text) async {
    final AmigaModel? model = _modelFrom(text);
    if (model == null) return text;

    final bool hasKickstart =
        RegExp(r'^kickstart_rom_file=\S', multiLine: true).hasMatch(text);
    final bool hasExtended =
        RegExp(r'^kickstart_ext_rom_file=\S', multiLine: true).hasMatch(text);
    if (hasKickstart && (!model.needsExtendedRom || hasExtended)) return text;

    final MediaIndex index = await MediaLibrary.cached();
    final List<MediaFile> roms = index.of(FileCategory.roms);
    if (roms.isEmpty) return text;

    final StringBuffer added = StringBuffer();
    if (!hasKickstart) {
      final MediaFile? rom = RomPicker.kickstartFor(model, roms);
      if (rom != null) added.writeln('kickstart_rom_file=${rom.path}');
    }
    if (model.needsExtendedRom && !hasExtended) {
      final MediaFile? ext = RomPicker.extendedRomFor(model, roms);
      if (ext != null) added.writeln('kickstart_ext_rom_file=${ext.path}');
    }
    if (added.isEmpty) return text;
    return '$added$text';
  }

  /// Re-points paths whose file has moved to wherever that file is now.
  ///
  /// Importing files them into the media folder, which means a setup made
  /// before an import names a path that no longer exists. The core does not
  /// treat that as an error - it reports "No disk in drive 0" and sits on the
  /// insert-disk screen - so the game simply never starts and nothing says
  /// why.
  ///
  /// Matching is by filename under the media folder, because that is what the
  /// import preserves: it moves a file between folders, never renames it.
  static Future<String> _relocateMissingMedia(String text) async {
    final String root = await MediaRoot.path();
    if (!Directory(root).existsSync()) return text;

    String result = text;
    for (final String path in mediaPathsIn(text)) {
      if (File(path).existsSync()) continue;

      final int slash = path.lastIndexOf('/');
      final String name = slash < 0 ? path : path.substring(slash + 1);

      final String? found = _findUnder(Directory(root), name);
      if (found != null) {
        result = result.replaceAll(path, found);
      }
    }
    return result;
  }

  /// Looks for [name] directly in [root] and one level down, which is the
  /// whole of the media folder's layout. A full walk would be slow and could
  /// match something in a game's own directory tree.
  static String? _findUnder(Directory root, String name) {
    for (final FileSystemEntity entry in root.listSync()) {
      if (entry is File && entry.path.endsWith('/$name')) return entry.path;
      if (entry is Directory) {
        final File candidate = File('${entry.path}/$name');
        if (candidate.existsSync()) return candidate.path;
      }
    }
    return null;
  }

  /// Matches everything up to and including the container UUID's slash, so the
  /// replacement keeps whatever follows (Documents/..., Library/...).
  static final RegExp _containerPrefix = RegExp(
    r'/[^\s=]*/Containers/Data/Application/[0-9A-Fa-f-]{36}/',
  );

  /// Every absolute path a config file names.
  ///
  /// Works on the text rather than a key list because the core has many
  /// path-valued keys - floppy0..3, hardfile2, filesystem2, uaehf0.., cdimage0,
  /// kickstart_rom_file - and several take a path in the middle of a
  /// comma-separated value rather than as the whole of it.
  static List<String> mediaPathsIn(String configText) {
    final Set<String> paths = <String>{};
    for (final String line in configText.split('\n')) {
      final int equals = line.indexOf('=');
      if (equals < 0) continue;
      for (final String part in line.substring(equals + 1).split(',')) {
        final String value = part.trim().replaceAll('"', '');
        // An absolute path with an extension: enough to exclude the drive
        // names, flags and numbers that share these lines.
        if (value.startsWith('/') && value.contains('.')) {
          paths.add(value);
        }
      }
    }
    return paths.toList();
  }

  static Future<List<SavedConfig>> list() async {
    final Directory dir = await configDirectory();
    final List<SavedConfig> configs = <SavedConfig>[];

    for (final FileSystemEntity entity in dir.listSync()) {
      if (entity is! File) continue;
      final String name = entity.uri.pathSegments.last;
      if (!name.endsWith('.uae')) continue;
      if (name.startsWith('.')) continue; // scratch configs

      String text;
      try {
        text = entity.readAsStringSync();
      } on Exception {
        continue;
      }
      configs.add(
        SavedConfig(
          name: name.substring(0, name.length - 4),
          path: entity.path,
          model: _modelFrom(text),
          summary: _summaryFrom(text),
          mediaPaths: mediaPathsIn(text),
        ),
      );
    }

    configs.sort(
      (SavedConfig a, SavedConfig b) =>
          a.name.toLowerCase().compareTo(b.name.toLowerCase()),
    );
    return configs;
  }

  static Future<void> delete(String path) async {
    final File file = File(path);
    if (file.existsSync()) file.deleteSync();
  }

  static String? _value(String text, String key) {
    for (final String line in text.split('\n')) {
      final int eq = line.indexOf('=');
      if (eq <= 0) continue;
      if (line.substring(0, eq).trim() == key) {
        return line.substring(eq + 1).trim();
      }
    }
    return null;
  }

  /// Infers the machine from what the config asks for. The core has no single
  /// "model" key: a setup is described by its chipset, CPU and CD hardware, so
  /// this reads those back the same way the launcher's parser did.
  static AmigaModel? _modelFrom(String text) {
    if (_value(text, 'cd32cd') == 'true') return AmigaModel.cd32;
    if (_value(text, 'cdtv') == 'true') return AmigaModel.cdtv;

    final String chipset = _value(text, 'chipset') ?? '';
    final int cpu = int.tryParse(_value(text, 'cpu_model') ?? '') ?? 68000;

    if (chipset == 'aga') {
      if (cpu >= 68040) return AmigaModel.a4000;
      return AmigaModel.a1200;
    }
    if (cpu >= 68030) return AmigaModel.a3000;
    if (chipset.startsWith('ecs')) return AmigaModel.a600;
    return AmigaModel.a500;
  }

  static String _summaryFrom(String text) {
    final List<String> parts = <String>[];

    final String? whd = _value(text, 'whdload_filename');
    if (whd != null && whd.isNotEmpty) {
      parts.add('WHDLoad: ${_baseName(whd)}');
    }
    final String? cd = _value(text, 'cdimage0');
    if (cd != null && cd.isNotEmpty) {
      parts.add('CD: ${_baseName(cd.replaceAll(RegExp(r',image$'), ''))}');
    }
    final String? df0 = _value(text, 'floppy0');
    if (df0 != null && df0.isNotEmpty) {
      parts.add('DF0: ${_baseName(df0)}');
    }
    for (final String line in text.split('\n')) {
      if (line.startsWith('hardfile2=') || line.startsWith('filesystem2=')) {
        parts.add('Hard drive');
        break;
      }
    }
    return parts.isEmpty ? 'No media' : parts.join(' · ');
  }

  static String _baseName(String path) {
    final String cleaned = path.replaceAll('"', '');
    final int slash = cleaned.lastIndexOf(RegExp(r'[/\\]'));
    return slash < 0 ? cleaned : cleaned.substring(slash + 1);
  }
}
